sudo: false

git:
  depth: 1

branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

# cache node modules
cache:
  directories:
    - node_modules

node_js:
  - '8'

before_install:
  # remove outdated deps, assists with cache maintenance
  - npm prune
